//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmd.EatUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Achievements = new HashSet<Achievements>();
            this.Meetings = new HashSet<Meetings>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ImagePath { get; set; }
        public string Room { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual ICollection<Achievements> Achievements { get; set; }
        public virtual ICollection<Meetings> Meetings { get; set; }
    }
}
