//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmd.EatUp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        public Meetings()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public int PlaceId { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
